# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArchitectureDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ArchitectureDemo
  pod 'YYModel', '~> 1.0.4'
  pod 'ReactiveObjC', '~> 3.1.0'

  target 'ArchitectureDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArchitectureDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
